// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewqaaboakbgonyngkzpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3cWFhYm9ha2Jnb255bmdrenB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0NTUxNTEsImV4cCI6MjA1MDAzMTE1MX0.zfEIZKfqXgPG1PWSbdslJMvby3Xo3kX3donTTkFUP7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);